spring:
  data:
    mongodb:
      uri: mongodb+srv://${USER}:${PASSWORD}@countrymanagement.dpzpz6k.mongodb.net/?retryWrites=true&w=majority
      database: management
  graphql:
    graphiql:
      enabled: true